services:
# Redis
 redis:
  image: redis:6.2
  container_name: redis
  restart: always
  hostname: redis
  privileged: true
  ports:
    - 16379:6379
  volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf
  networks:
    - my-network
  healthcheck:
    test: [ "CMD", "redis-cli", "ping" ]
    interval: 10s
    timeout: 5s
    retries: 3

# RedisAdmin https://github.com/joeferner/redis-commander
 redis-admin:
  image: spryker/redis-commander:0.8.0
  container_name: redis-admin
  hostname: redis-commander
  restart: always
  ports:
    - 8081:8081
  environment:
    - REDIS_HOSTS=local:redis:6379
    - HTTP_USER=admin
    - HTTP_PASSWORD=admin
    - LANG=C.UTF-8
    - LANGUAGE=C.UTF-8
    - LC_ALL=C.UTF-8
  networks:
    - my-network
  depends_on:
    redis:
      condition: service_healthy

networks:
  my-network:
    driver: bridge